# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 #none, main, ce qui declanche le pipeline
trigger:
- main

pool:
  vmImage: windows-latest
variables:
  buildConfig: 'Release'

steps:
 
- task: DotNetCoreCLI@2
  displayName: 'restauration des packages NuGet'
  inputs:
    command: 'restore'
    projects: '*.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'generation de la solution'
  inputs:
    command: 'build'
    projects: '*.csproj'
    arguments: '--configuration $(Release)'
#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'test'
#    projects: '*UnitTests.csproj'

#    arguments: '--configuration $(Release)'
- task: DotNetCoreCLI@2
  displayName: 'publication du projet'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(Release) --output $(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'publication de artefact azure pipeline'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'